### ISSUE TITLE
real macbook pro mid 2015

### ISSUE THREAD

**Issue by Vorshim92** [chris1111/Command-Line-SnapShot-Mounter#1]
hi! I was trying your Snapshot Mounter on a real macbook pro 2015 with SIP disabled and with last update of big sur 11.6.6 but when I mount the disk1s1 of my APFS everything goes right but in the new mounted volume doesnt appears nothing, blank folder so I think it doesn't work. any idea? 

![171999389-54f12fd5-cc49-4124-8c57-a226990809ad](https://user-images.githubusercontent.com/6248794/172000427-247bc933-d3d7-4e06-82ab-08d99ef52277.jpeg)

**Comment by chris1111** [comment]
disk1s1 is not a real snapshot, look at the guide as it should and try to mount up the right Volume

**Comment by Vorshim92** [comment]
omg. in my case disk1s1 was the partition "Data", I know how it works, it wasn't the EFI... why don't try to give some real answer or help instead of closing the issue just like this. Like, This tool supposed to work also on a real macbook? is there any chance that doesn't work with this update?

**Comment by chris1111** [comment]
The real snapshot is disk1s5
