### ISSUE TITLE
macbook pro mid 2015 error in mounting 

### ISSUE THREAD

**Issue by Vorshim92** [chris1111/Command-Line-SnapShot-Mounter#2]
Hi again Chris. I already wrote you in the issue before, can you try to help me? is there a chance that your tool doesn't work anymore on last update of big sur? or maybe is something also? I already disable SIP and csrutil authenticated-root but nothing.
here some screen (and no, it wasn't the efi partition "disk1s1"....)
![photo_2022-06-04_14-41-04](https://user-images.githubusercontent.com/7747380/171999389-54f12fd5-cc49-4124-8c57-a226990809ad.jpg)
![photo_2022-06-04_14-38-40](https://user-images.githubusercontent.com/7747380/171999391-9e9a1aad-0772-4035-a16c-b46face7e703.jpg)

**Comment by chris1111** [comment]
Why open another issue you have one [here](https://github.com/chris1111/Command-Line-SnapShot-Mounter/issues/1)

**Comment by chris1111** [comment]
Your APFS Volume is disk1s5

**Comment by Vorshim92** [comment]
> Why open another issue you have one [here](https://github.com/chris1111/Command-Line-SnapShot-Mounter/issues/1)

it that real important? can we focus on the problem?

**Comment by chris1111** [comment]
> Your APFS Volume is disk1s5

Yes its important !!!!!!!!

Your APFS Volume is disk1s5
This is not an issue, it will be deleted
