### ISSUE TITLE
Trying to install AppleFWAudio.kext on Sonoma

### ISSUE THREAD

**Issue by northwinds** [chris1111/Command-Line-SnapShot-Mounter#3]
Hi there
I was trying to use your Command-Line-SnapShot-Mounter to add my AppleFWAudio.kext to my Sonoma opencore system. Up until last week it was working fine with the kext in the EFI allowing me to use my Focusrite Daffire Pro 24 DSOP card - which cost me several hundred pounds!
As I don't have any work right now replacing this isn't an option.
Can you please help?

I'm attaching the text from Command-Line-SnapShot-Mounter below.

Many thanks!
[Terminal Saved Output.txt](https://github.com/chris1111/Command-Line-SnapShot-Mounter/files/14526988/Terminal.Saved.Output.txt)

**Comment by chris1111** [comment]
This script work on macOS Monterey 12 and Big Sur 11 only 
Did you try to install the kext in /Library/Extensions with the command

`sudo touch "${3}/Library/Extensions/"`
Then allow the kext in Preference System / Security

**Comment by northwinds** [comment]
> This script work on macOS Monterey 12 and Big Sur 11 only 
Did you try to install the kext in /Library/Extensions with the command
> 
> `sudo touch "${3}/Library/Extensions/"` 
Then allow the kext in Preference System / Security

Ah, I'll give that a try - thanks, Chris!
